#!/bin/bash
#
sudo /home/pi/github/climberhunt/uvc-gadget/multi-gadget.sh
/usr/bin/v4l2-ctl -c auto_exposure=0
/usr/bin/v4l2-ctl -c auto_exposure_bias=8
/usr/bin/v4l2-ctl -c contrast=20
/usr/bin/v4l2-ctl -c video_bitrate=25000000
sudo /home/pi/github/climberhunt/uvc-gadget/uvc-gadget -f1 -s1 -r1  -u /dev/video1 -v /dev/video0

